# file: rols/eclipse/tasks/main.yml

# download and extract eclipse luna sr2



- name: download eclipse luna sr2
  with_nested: 
    - local_users
    - eclipse
  get_url: url={{ item.1.server }}/{{ item.1.version }}/{{ item.1.archive }} dest=/home/{{ item.0.user }}/Downloads
