# file: roles/ci/tasks

#
# Install and start jenkins CI
#

- name: Install jenkins CI server
  with_items:
  - jenkins
  yum: name="{{ item }}"

- name: Start jenkins CI server
  service: name=jenkins enabled=yes state=started
