# common tasks

- name: Common packages
  with_items:
  - git
  - maven
  - curl
  - nano
  - wget
  - python-boto
  - docker
  apt: name={{ item }} state=present force=yes

- name: Let's enable SSH server if it's not already enabled
  service: name=ssh enabled=yes state=started
